# permissions to do viewer databasebenchmarkruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databasebenchmarkrun-viewer-role
rules:
- apiGroups:
  - benchmark.cloud.shuosc.org
  resources:
  - databasebenchmarkruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - benchmark.cloud.shuosc.org
  resources:
  - databasebenchmarkruns/status
  verbs:
  - get
