# permissions to do edit databasebenchmarkprepares.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databasebenchmarkprepare-editor-role
rules:
- apiGroups:
  - benchmark.cloud.shuosc.org
  resources:
  - databasebenchmarkprepares
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - benchmark.cloud.shuosc.org
  resources:
  - databasebenchmarkprepares/status
  verbs:
  - get
  - patch
  - update
