# permissions to do viewer databasebenchmarkprepares.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databasebenchmarkprepare-viewer-role
rules:
- apiGroups:
  - benchmark.cloud.shuosc.org
  resources:
  - databasebenchmarkprepares
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - benchmark.cloud.shuosc.org
  resources:
  - databasebenchmarkprepares/status
  verbs:
  - get
