
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - benchmark.cloud.shuosc.org
  resources:
  - databasebenchmarkprepares
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - benchmark.cloud.shuosc.org
  resources:
  - databasebenchmarkprepares/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - benchmark.tidb.pingcap.com.benchmark.pingcap.com
  resources:
  - tpccbenchmarks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - benchmark.tidb.pingcap.com.benchmark.pingcap.com
  resources:
  - tpccbenchmarks/status
  verbs:
  - get
  - patch
  - update
