# permissions to do viewer tpccbenchmarks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tpccbenchmark-viewer-role
rules:
- apiGroups:
  - benchmark.cloud.shuosc.org
  resources:
  - tpccbenchmarks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - benchmark.cloud.shuosc.org
  resources:
  - tpccbenchmarks/status
  verbs:
  - get
