apiVersion: benchmark.cloud.shuosc.org/v1alpha1
kind: DataBaseBenchmarkPrepare
metadata:
  name: benchmark-prepare-sample
spec:
  host: demo-mysql-svc
  port: 3306
  user: demo
  password: demo
  prepares:
    - type: sysbench
      database: sbsbtest
      image: severalnines/sysbench
      params:
        tablesize: "100000"
        tablescount: "24"
        threads: "1"