apiVersion: benchmark.cloud.shuosc.org/v1alpha1
kind: DataBaseBenchmarkRun
metadata:
  name: benchmark-run-sample
spec:
  host: demo-mysql-svc
  port: 3306
  user: demo
  password: demo
  runs:
    - type: sysbench
      database: sbtest
      image: severalnines/sysbench
      params:
        tablesize: "100000"
        tablescount: "24"
        threads: "16"
        report-interval: "10"
        time: "60"
