name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd ./images/benchmarksql
# todo: build docker image here
# eg.
#        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/benchmarksql:$(date +%s)
#        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#        docker push ${{ secrets.DOCKER_USERNAME }}/benchmarksql
